### ISSUE TITLE
I am missing the machine learning supervised algorithms.

### ISSUE THREAD

**Issue by brammittendorff-dd** [AnykeyNL/CrimeBusterBot#4]
In your README.md you describe there is an additional feature:
- The product also detects other similar websites using content analysis and machine learning supervised algorithms.

I was curious so I checked some python scripts but I can not find a training set, models nor something that looks like machine learning. Could you please provide us the machine learning code?

**Comment by olexandrpi** [comment]
Hi! There is no code for the machine learning part. We used Microsoft's ML tools for that. @pcmill can tell you more.

**Comment by pcmill** [comment]
Yes! We used a tool called customvision.ai. This allowed us to quickly iterate and prototype. If we had a bit more time we could have exported the Tensorflow model and hooked it up to our DNS crawler. This way the crawler gives us the network of webshops and the machine learning model can show us if it is indeed malicious. Now ofcourse in real life you would need to do a lot more checks, see the SSL check we build.

**Comment by olexandrpi** [comment]
btw, the content analysis can also be done with ML pattern recognition algorithms, but we did not implement that, of course, due to the little time.

**Comment by mjrider** [comment]
@pcmill to bad that the cert check tool is checking the CN field, where you should be checking the SAN fields. now you are checking for `CN=sni252263.cloudflaressl.com` instead of the real domain name.

if i read the code correctly:
- no SNI, so no checking of sites with multiple sites per IP ( which is very common )
- no checking of SAN fields, so no support for cloudflare e.g.

**Comment by olexandrpi** [comment]
Thank you for commenting on the features.

This project was made in 16 hours - it may happen, that we did not implement all the options. If there is any interest in this project, we can discuss the opportunities to continue working on it.

But feel free to open discussions with possible improvements.
