### ISSUE TITLE
Little thingy

### ISSUE THREAD

**Issue by Annihilator708** [AnykeyNL/CrimeBusterBot#5]
So, unfortunately this project is completely locked from forks or whatever. Never the less i took my time to remove unnecessary stuff. Since I don't want to throw work away ill post it this way. Perhaps you could fix it with copy pasta if you know what i mean ;).
Anyways I would like to point a couple things out. Those points are not major but could be helpful to prevent annoying bugs in the future. Your indentation in `Check.py` is made out of tabs instead of 4 spaces like the rest of your software. 

`Note: Please test before using it :p`

Here I changed it for you:
```py
#!/usr/local/bin env
# -*- coding: utf8 -*-

# written for python 2!
# had issues getting mysql working for python 3 :-(
"""
perhaps try sqlite or postgres :)
"""

import MySQLdb
import urllib2
import sys

db = MySQLdb.connect("localhost","root","hackathon","cbb")
cursor = db.cursor()

def CheckLinks(url):
    fakes = open("fakesites_{}.txt".format(url),"w")
    countfake = 0
    db = MySQLdb.connect("localhost","root","hackathon","cbb")
    cursor = db.cursor()


    q = "select domain, ns from SIDN where domain like '%{}%'".format(url)
    cursor.execute(q)
    #data = cursor.fetchone()
    print("Finding source DNS for {}".format(url))
    #ns = "ns81.domaincontrol.com"
    #for domain,ns in cursor:a
    for domain,ns in cursor:
        print("Source is {}".format(ns))

        print("Scanning for websites from same source, using same html template:")
        q = "select domain, ns from SIDN where ns= '{}'".format(ns)
        c2 = db.cursor()
        c2.execute(q)
        for domain,ns in c2:
            domain = domain.strip()
            #print(domain)

            # see if they contain shopping cart
            try:
            #if True:
                url = "http://www.{}.nl".format(domain)

                content = urllib2.urlopen(url).read()
                if content.find("shopping_cart") > 0 or content.find("checkout") > 0:
                    fakes.write("{}\n".format(url))
                    countfake = countfake + 1
                    print("{} has simular webshop template, likely bogus!".format(url))
            except:
                f = 1 # skip
                # print("error")
            #if countfake > 3:
            #    break
    fakes.close()

url = sys.argv[1:]

if len(url) == 1:
    url = url[0]
    print("Background check on: {}".format(url))
    CheckLinks(url)
else:
    print("What you want me to check")
```
Perhaps you also noticed already the shebang on the top of the file.
In "PoliceCheck.py" is a unused import of json and "cer_check.py" includes time which is not used.

I hope it helped a little. Like i said its not major thing or anything, would love to upload it myself instead :p

Anyways,

Have a great day 👋

**Comment by olexandrpi** [comment]
Thank you for the comments and improvements. We are aware of the most of them, since we are not a real team. We just gathered together for this project and we did not discuss any styling etc. Some of us even do not know what PEP8 is and how to use `pylint` or `flake8`.

Most probably, this project will not be extended and can even be deleted, since the police is interested in having it for themselves. In any case, the data used here is confidential and will not be published, so this code is pretty useless without that data.

**Comment by Annihilator708** [comment]
The idea of the project is great :) 

Sad to hear it could end here. Either way thank you for the kind information!

**Comment by AnykeyNL** [comment]
We really do not hope it ends here. We will continue this research if we get an extension of using the data (which I think we will get). We are already planning meetings with the dutch police and SIDN to discuss further development. I just do not think something public will be made available in the near term.

**Comment by Annihilator708** [comment]
The idea of collecting images from websites to compare them with the official website to detect phishing websites is something really interesting to me. Before I knew about this project i was planning ahead to make a system that could actively scan the WWW for this kind of websites with the method just described. I figured you guys already made a start :+1: like i mentioned before, great idea. Keep the work up ^^
